apiVersion: apps/v1
kind: Deployment                          # type of object we are creating, here we are creating of type "Deployment"
metadata:                                 # Details about above Object - "Deployment"
  name:   zuul-server-deployment              # name of above object - "Deployment"


spec:                                     # specification of "Deployment" object 
  replicas: 1                             # 1 pod will be created by "Deployment" config
  
  selector: 
    matchLabels:
      component: zuul-server        # key to match with pod -> line number: 17 
  
  template:                               # template is the configuration of pods - Pod Template 
    
    metadata: 
      labels: 
        component: zuul-server     # key to map with "Service" object
    
    spec:                                 # specification of Pod
      containers:                         #container configuration -
        - name: zuul-server-container
          # image: ravisaditya/zuul-server
          image: 711669183136.dkr.ecr.ap-south-1.amazonaws.com/zuul-server    #for AWS
          imagePullPolicy: Always #what is the use of it?  Always enforce image force pull to avoid unexpected issues when k8s doesn't pull an image from a remote repository.
          ports: 
            - containerPort: 8008
          env: 
            - name: EUREKA_SERVER_ADDRESS
              valueFrom: 
                configMapKeyRef: 
                    name: zuul-config-map
                    key: eureka_server_address
            
            # - name: AWS_ECR_URL
            #   valueFrom: 
            #     secretKeyRef: 
            #         name: zuul-config-map
            #         key: aws-ecr-url
                
      #  AWS secret to pull the image      
      imagePullSecrets:
        - name: ravi-aws-ecr-repo-secret
   
        
      