apiVersion: apps/v1
kind: Deployment                          # type of object we are creating, here we are creating of type "Deployment"
metadata:                                 # Details about above Object - "Deployment"
  name:   auth-server-deployment              # name of above object - "Deployment"


spec:                                     # specification of "Deployment" object 
  replicas: 1                             # 3 pods will be created by "Deployment" config
  
  selector: 
    matchLabels:
      component: auth-server-ms        # key to match with pod -> line number: 17 
  
  template:                               # template is the configuration of pods - Pod Template 
    
    metadata: 
      labels: 
        component: auth-server-ms     # key to map with "Service" object -> prod -> product
    
    spec:                                 # specification of Pod
      containers:                         #container configuration
        - name: auth-server-container
          # image: ravisaditya/auth-server
          image: 711669183136.dkr.ecr.ap-south-1.amazonaws.com/eureka-server    #for AWS
          imagePullPolicy: Always #what is the use of it?  Always enforce image force pull to avoid unexpected issues when k8s doesn't pull an image from a remote repository.
          ports: 
            - containerPort: 8822
          env: 
            - name: EUREKA_SERVER_ADDRESS
              valueFrom: 
                configMapKeyRef: 
                    name: auth-server-config-map
                    key: eureka_server_address

      #  AWS secret to pull the image      
      imagePullSecrets:
        - name: ravi-aws-ecr-repo-secret
                
   
        
      