#This is headless service
apiVersion: v1
kind: Service
metadata:
  name: eureka
  labels:
    app: eureka
spec:
  clusterIP: None #cluster IP is none, this makes it headless
  ports:
    - port: 8000
      name: eureka
  selector:
    app: eureka